<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\KycDocumentType;

class KycDocumentTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $documentTypes = [
            // ========== KENYA ==========
            [
                'country_code' => 'KE',
                'document_key' => 'national_id',
                'display_name' => 'National ID',
                'local_name' => 'Kipande / Huduma Namba',
                'description' => 'Kenya National Identity Card or Huduma Namba card',
                'accepted_formats' => ['JPG', 'PNG', 'PDF'],
                'validation_rules' => ['pattern' => '^[0-9]{7,8}$', 'pattern_message' => 'ID number must be 7-8 digits'],
                'example_value' => '12345678',
                'requires_expiry' => false,
                'requires_front_back' => true,
                'requires_verification_api' => true,
                'verification_provider' => 'smile_id',
                'display_order' => 1,
                'category' => 'identity',
            ],
            [
                'country_code' => 'KE',
                'document_key' => 'selfie',
                'display_name' => 'Selfie Photo',
                'local_name' => null,
                'description' => 'A clear selfie photo for liveness verification',
                'accepted_formats' => ['JPG', 'PNG'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => true,
                'verification_provider' => 'smile_id',
                'display_order' => 2,
                'category' => 'identity',
            ],
            [
                'country_code' => 'KE',
                'document_key' => 'business_registration',
                'display_name' => 'Business Registration Certificate',
                'local_name' => 'CR12 / Certificate of Incorporation',
                'description' => 'Certificate of Registration or Incorporation from the Registrar of Companies',
                'accepted_formats' => ['PDF', 'JPG', 'PNG'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 3,
                'category' => 'business',
            ],
            [
                'country_code' => 'KE',
                'document_key' => 'kra_pin',
                'display_name' => 'KRA PIN Certificate',
                'local_name' => 'KRA PIN',
                'description' => 'Kenya Revenue Authority Personal Identification Number certificate',
                'accepted_formats' => ['PDF', 'JPG', 'PNG'],
                'validation_rules' => ['pattern' => '^[A-Z][0-9]{9}[A-Z]$', 'pattern_message' => 'KRA PIN must be in format A123456789Z'],
                'example_value' => 'A123456789Z',
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 4,
                'category' => 'business',
            ],
            [
                'country_code' => 'KE',
                'document_key' => 'bank_statement',
                'display_name' => 'Bank Statement',
                'local_name' => null,
                'description' => 'Recent bank statement (last 3-6 months)',
                'accepted_formats' => ['PDF'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 5,
                'category' => 'financial',
            ],
            [
                'country_code' => 'KE',
                'document_key' => 'ubo_declaration',
                'display_name' => 'Ultimate Beneficial Owner Declaration',
                'local_name' => null,
                'description' => 'Declaration of individuals who own 25% or more of the business',
                'accepted_formats' => ['PDF'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 6,
                'category' => 'business',
            ],

            // ========== UGANDA ==========
            [
                'country_code' => 'UG',
                'document_key' => 'national_id',
                'display_name' => 'National ID',
                'local_name' => 'Ndaga Muntu',
                'description' => 'Uganda National Identification Card',
                'accepted_formats' => ['JPG', 'PNG', 'PDF'],
                'validation_rules' => ['pattern' => '^[A-Z]{2}[0-9]{7}[A-Z]{5}[0-9]{2}$', 'pattern_message' => 'NIN must be in format CM12345678ABCDE12'],
                'example_value' => 'CM12345678ABCDE12',
                'requires_expiry' => false,
                'requires_front_back' => true,
                'requires_verification_api' => true,
                'verification_provider' => 'smile_id',
                'display_order' => 1,
                'category' => 'identity',
            ],
            [
                'country_code' => 'UG',
                'document_key' => 'selfie',
                'display_name' => 'Selfie Photo',
                'local_name' => null,
                'description' => 'A clear selfie photo for liveness verification',
                'accepted_formats' => ['JPG', 'PNG'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => true,
                'verification_provider' => 'smile_id',
                'display_order' => 2,
                'category' => 'identity',
            ],
            [
                'country_code' => 'UG',
                'document_key' => 'business_registration',
                'display_name' => 'Business Registration Certificate',
                'local_name' => 'URSB Certificate',
                'description' => 'Certificate of Registration from Uganda Registration Services Bureau',
                'accepted_formats' => ['PDF', 'JPG', 'PNG'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 3,
                'category' => 'business',
            ],
            [
                'country_code' => 'UG',
                'document_key' => 'tin_certificate',
                'display_name' => 'TIN Certificate',
                'local_name' => 'URA TIN',
                'description' => 'Tax Identification Number certificate from Uganda Revenue Authority',
                'accepted_formats' => ['PDF', 'JPG', 'PNG'],
                'validation_rules' => ['pattern' => '^[0-9]{10}$', 'pattern_message' => 'TIN must be 10 digits'],
                'example_value' => '1234567890',
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 4,
                'category' => 'business',
            ],
            [
                'country_code' => 'UG',
                'document_key' => 'bank_statement',
                'display_name' => 'Bank Statement',
                'local_name' => null,
                'description' => 'Recent bank statement (last 3-6 months)',
                'accepted_formats' => ['PDF'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 5,
                'category' => 'financial',
            ],
            [
                'country_code' => 'UG',
                'document_key' => 'ubo_declaration',
                'display_name' => 'Ultimate Beneficial Owner Declaration',
                'local_name' => null,
                'description' => 'Declaration of individuals who own 25% or more of the business',
                'accepted_formats' => ['PDF'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 6,
                'category' => 'business',
            ],

            // ========== RWANDA ==========
            [
                'country_code' => 'RW',
                'document_key' => 'national_id',
                'display_name' => 'National ID',
                'local_name' => 'Indangamuntu',
                'description' => 'Rwanda National Identity Card',
                'accepted_formats' => ['JPG', 'PNG', 'PDF'],
                'validation_rules' => ['pattern' => '^[0-9]{16}$', 'pattern_message' => 'NID must be 16 digits'],
                'example_value' => '1199880012345678',
                'requires_expiry' => false,
                'requires_front_back' => true,
                'requires_verification_api' => true,
                'verification_provider' => 'smile_id',
                'display_order' => 1,
                'category' => 'identity',
            ],
            [
                'country_code' => 'RW',
                'document_key' => 'selfie',
                'display_name' => 'Selfie Photo',
                'local_name' => null,
                'description' => 'A clear selfie photo for liveness verification',
                'accepted_formats' => ['JPG', 'PNG'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => true,
                'verification_provider' => 'smile_id',
                'display_order' => 2,
                'category' => 'identity',
            ],
            [
                'country_code' => 'RW',
                'document_key' => 'business_registration',
                'display_name' => 'Business Registration Certificate',
                'local_name' => 'RDB Certificate',
                'description' => 'Certificate of Registration from Rwanda Development Board',
                'accepted_formats' => ['PDF', 'JPG', 'PNG'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 3,
                'category' => 'business',
            ],
            [
                'country_code' => 'RW',
                'document_key' => 'rra_tin',
                'display_name' => 'TIN Certificate',
                'local_name' => 'RRA TIN',
                'description' => 'Tax Identification Number from Rwanda Revenue Authority',
                'accepted_formats' => ['PDF', 'JPG', 'PNG'],
                'validation_rules' => ['pattern' => '^[0-9]{9}$', 'pattern_message' => 'TIN must be 9 digits'],
                'example_value' => '123456789',
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 4,
                'category' => 'business',
            ],
            [
                'country_code' => 'RW',
                'document_key' => 'bank_statement',
                'display_name' => 'Bank Statement',
                'local_name' => null,
                'description' => 'Recent bank statement (last 3-6 months)',
                'accepted_formats' => ['PDF'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 5,
                'category' => 'financial',
            ],
            [
                'country_code' => 'RW',
                'document_key' => 'ubo_declaration',
                'display_name' => 'Ultimate Beneficial Owner Declaration',
                'local_name' => null,
                'description' => 'Declaration of individuals who own 25% or more of the business',
                'accepted_formats' => ['PDF'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 6,
                'category' => 'business',
            ],

            // ========== ZAMBIA ==========
            [
                'country_code' => 'ZM',
                'document_key' => 'nrc',
                'display_name' => 'National Registration Card',
                'local_name' => 'NRC',
                'description' => 'Zambia National Registration Card (Green Card)',
                'accepted_formats' => ['JPG', 'PNG', 'PDF'],
                'validation_rules' => ['pattern' => '^[0-9]{6}/[0-9]{2}/[0-9]$', 'pattern_message' => 'NRC must be in format 123456/12/1'],
                'example_value' => '123456/12/1',
                'requires_expiry' => false,
                'requires_front_back' => true,
                'requires_verification_api' => true,
                'verification_provider' => 'smile_id',
                'display_order' => 1,
                'category' => 'identity',
            ],
            [
                'country_code' => 'ZM',
                'document_key' => 'selfie',
                'display_name' => 'Selfie Photo',
                'local_name' => null,
                'description' => 'A clear selfie photo for liveness verification',
                'accepted_formats' => ['JPG', 'PNG'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => true,
                'verification_provider' => 'smile_id',
                'display_order' => 2,
                'category' => 'identity',
            ],
            [
                'country_code' => 'ZM',
                'document_key' => 'pacra_certificate',
                'display_name' => 'PACRA Certificate',
                'local_name' => 'Certificate of Incorporation',
                'description' => 'Certificate of Incorporation from Patents and Companies Registration Agency',
                'accepted_formats' => ['PDF', 'JPG', 'PNG'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 3,
                'category' => 'business',
            ],
            [
                'country_code' => 'ZM',
                'document_key' => 'tpin_certificate',
                'display_name' => 'TPIN Certificate',
                'local_name' => 'ZRA TPIN',
                'description' => 'Taxpayer Identification Number from Zambia Revenue Authority',
                'accepted_formats' => ['PDF', 'JPG', 'PNG'],
                'validation_rules' => ['pattern' => '^[0-9]{10}$', 'pattern_message' => 'TPIN must be 10 digits'],
                'example_value' => '1234567890',
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 4,
                'category' => 'business',
            ],
            [
                'country_code' => 'ZM',
                'document_key' => 'bank_statement',
                'display_name' => 'Bank Statement',
                'local_name' => null,
                'description' => 'Recent bank statement (last 3-6 months)',
                'accepted_formats' => ['PDF'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 5,
                'category' => 'financial',
            ],
            [
                'country_code' => 'ZM',
                'document_key' => 'ubo_declaration',
                'display_name' => 'Ultimate Beneficial Owner Declaration',
                'local_name' => null,
                'description' => 'Declaration of individuals who own 25% or more of the business',
                'accepted_formats' => ['PDF'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 6,
                'category' => 'business',
            ],

            // ========== NIGERIA ==========
            [
                'country_code' => 'NG',
                'document_key' => 'nin',
                'display_name' => 'National Identification Number',
                'local_name' => 'NIN',
                'description' => 'Nigeria National Identification Number',
                'accepted_formats' => ['JPG', 'PNG', 'PDF'],
                'validation_rules' => ['pattern' => '^[0-9]{11}$', 'pattern_message' => 'NIN must be 11 digits'],
                'example_value' => '12345678901',
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => true,
                'verification_provider' => 'smile_id',
                'display_order' => 1,
                'category' => 'identity',
            ],
            [
                'country_code' => 'NG',
                'document_key' => 'selfie',
                'display_name' => 'Selfie Photo',
                'local_name' => null,
                'description' => 'A clear selfie photo for liveness verification',
                'accepted_formats' => ['JPG', 'PNG'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => true,
                'verification_provider' => 'smile_id',
                'display_order' => 2,
                'category' => 'identity',
            ],
            [
                'country_code' => 'NG',
                'document_key' => 'bvn',
                'display_name' => 'Bank Verification Number',
                'local_name' => 'BVN',
                'description' => 'Bank Verification Number for identity verification',
                'accepted_formats' => [],
                'validation_rules' => ['pattern' => '^[0-9]{11}$', 'pattern_message' => 'BVN must be 11 digits'],
                'example_value' => '12345678901',
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => true,
                'verification_provider' => 'youverify',
                'display_order' => 3,
                'category' => 'identity',
            ],
            [
                'country_code' => 'NG',
                'document_key' => 'cac_certificate',
                'display_name' => 'CAC Certificate',
                'local_name' => 'Certificate of Incorporation',
                'description' => 'Certificate of Incorporation from Corporate Affairs Commission',
                'accepted_formats' => ['PDF', 'JPG', 'PNG'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 4,
                'category' => 'business',
            ],
            [
                'country_code' => 'NG',
                'document_key' => 'tin_certificate',
                'display_name' => 'TIN Certificate',
                'local_name' => 'FIRS TIN',
                'description' => 'Tax Identification Number from Federal Inland Revenue Service',
                'accepted_formats' => ['PDF', 'JPG', 'PNG'],
                'validation_rules' => ['pattern' => '^[0-9]{8}-[0-9]{4}$', 'pattern_message' => 'TIN must be in format 12345678-1234'],
                'example_value' => '12345678-1234',
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 5,
                'category' => 'business',
            ],
            [
                'country_code' => 'NG',
                'document_key' => 'bank_statement',
                'display_name' => 'Bank Statement',
                'local_name' => null,
                'description' => 'Recent bank statement (last 3-6 months)',
                'accepted_formats' => ['PDF'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 6,
                'category' => 'financial',
            ],
            [
                'country_code' => 'NG',
                'document_key' => 'ubo_declaration',
                'display_name' => 'Ultimate Beneficial Owner Declaration',
                'local_name' => null,
                'description' => 'Declaration of individuals who own 25% or more of the business',
                'accepted_formats' => ['PDF'],
                'validation_rules' => null,
                'example_value' => null,
                'requires_expiry' => false,
                'requires_front_back' => false,
                'requires_verification_api' => false,
                'verification_provider' => null,
                'display_order' => 7,
                'category' => 'business',
            ],
        ];

        foreach ($documentTypes as $docType) {
            KycDocumentType::updateOrCreate(
                [
                    'country_code' => $docType['country_code'],
                    'document_key' => $docType['document_key'],
                ],
                $docType
            );
        }
    }
}
